.PHONY: clean All

All:
	@echo "----------Building project:[ bocabajo - Debug ]----------"
	@"$(MAKE)" -f  "bocabajo.mk"
clean:
	@echo "----------Cleaning project:[ bocabajo - Debug ]----------"
	@"$(MAKE)" -f  "bocabajo.mk" clean
