.PHONY: clean All

All:
	@echo "----------Building project:[ delreves - Debug ]----------"
	@"$(MAKE)" -f  "delreves.mk"
clean:
	@echo "----------Cleaning project:[ delreves - Debug ]----------"
	@"$(MAKE)" -f  "delreves.mk" clean
