.PHONY: clean All

All:
	@echo "----------Building project:[ secuencia - Debug ]----------"
	@"$(MAKE)" -f  "secuencia.mk"
clean:
	@echo "----------Cleaning project:[ secuencia - Debug ]----------"
	@"$(MAKE)" -f  "secuencia.mk" clean
